# -*- coding: utf-8 -*-
"""1. Listas enlazadas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UIKSZU0A2MQO1neW-7CV-xAYP-3jgIPj
"""

print("Nombre: Alvaro Socop Carne : 202000194")


## Definición de la clase Estudiante


class estudiante:
  def __init__(self, carne, nombre, edad, direccion, telefono, email, carrera, puesto): #el self es como el this de java, indicandole que los atributos pertenecen a esa clase
    self.carne = carne
    self.nombre = nombre
    self.edad = edad
    self.direccion = direccion
    self.telefono = telefono
    self.email = email
    self.carrera = carrera
    self.puesto = puesto

"""### **Definición de la clase nodo**"""

class nodo:
  def __init__(self, estudiante=None, siguiente=None): #al construir funciones constructoras se le puede dar valores a los parametros que nosotros enviemos
    self.estudiante = estudiante
    self.siguiente = siguiente

"""**Definición de la clase Lista Enlazada**"""

#creación , insercion, eliminación, busqueda
class lista_enlazada:
  def __init__(self): #cuando la lista está vacía, solo tendriamos la lista con un elemento sin nada
    #el elemento esta esperando a que se le agreguen nodos transformandolo en el nodo que se le envie como primero.
    self.primero = None #al principio apunta a vacio
  def insertar(self, est):
    if self.primero is None:
      self.primero=nodo(estudiante=est) #estudiante es la variable que se encuentra en la clase Nodo
      return 
    actual = self.primero
    while actual.siguiente: # y que pasa si el primero no es vacío? seria la segunda iteración
      actual=actual.siguiente
    actual.siguiente=nodo(estudiante=est)

  def recorrer(self):
    actual=self.primero
    while actual !=None:
      print("carne: ", actual.estudiante.carne, "NOMBRE: ", actual.estudiante.nombre, "email: ", actual.estudiante.email, "-->")
      actual = actual.siguiente
  def eliminar(self, carne):
    actual = self.primero
    anterior = None
    while actual and actual.estudiante.carne != carne:
      anterior=actual
      actual=actual.siguiente
    if anterior is None:
      self.primero=actual.siguiente
      actual.siguiente=None
    elif actual:
      actual.siguiente=actual.siguiente
      actual.siguiente=None

  def search_node(self, carne):
    actual=self.primero
    anterior=None
    while actual and actual.estudiante.carne != carne:
      anterior=actual
      actual=actual.siguiente
      print("hola")         
    if actual:
      print("se ha encontrado y es: ", "carne: ", actual.estudiante.carne, "NOMBRE: ", actual.estudiante.nombre, "email: ", actual.estudiante.email, "-->" )

"""### **Creacion de objetos Estudiante**"""

e1=estudiante(202000194, "Alvaro Socop",20, "CASA", 57707472, "socop2412@gmail.com", "Ingenieria en Sistemas", "Estudiante")
e2=estudiante(123456, "Gerardy Mandela", "Cayala",15, 65849852, "6515198@gmail.com", "Ingenieria en Mecatrónica", "Estudiante")
e3=estudiante(4444444, "Albert Einstein",18, "Villa Hermosa", 64198189, "6549819@gmail.com", "Ingenieria Orgánica", "Estudiante")
e4=estudiante(123456789, "Miguel Cardona",16, "Villa Nueva", 9849819812, "65195898@gmail.com", "Ingenieria Química", "Estudiante")

"""### **Inserción*"""

lista_e = lista_enlazada()
lista_e.insertar(e1)
lista_e.insertar(e2)
lista_e.insertar(e3)
lista_e.insertar(e4)

"""### **Recorrer Lista**"""

lista_e.recorrer()

"""Nodos:
1er > 2do > 3ero

Gerson > Karen > Luis

### **Eliminar un nodo lista**
"""

lista_e.eliminar(202000194)
lista_e.recorrer()

"""## **Buscar un nodo lista**"""

lista_e.search_node(123456)

"""### *ejemplos extras: *"""

def test(x, y=1):
  if y==1:
    print("true")
  else:
    print("false")

test(10,0)

